name: check
on:
    - push
jobs:
    build-and-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 18.20
            - run: npm ci
            - run: npm run build
            - run: npm run format:check
            - run: npm run lint:check
